spring:
    application:
      name: tournament-itatiba-open-app
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
    datasource:
      url: jdbc:postgresql://localhost:5432/tournament_itatiba_open_db
      username: postgres
      password: 91710956
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 30000
        max-lifetime: 600000
        connection-timeout: 20000
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          use_sql_comments: true

server:
  port: 8081