spring:
    application:
      name: tournament-itatiba-open-app
    datasource:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_POST:5432}/${DB_NAME:tournament_itatiba_open_db}
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 30000
        max-lifetime: 600000
        connection-timeout: 20000
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          use_sql_comments: true

eureka:
  client:
    service-url:
      defaultZone: http://${NAMING_SERVER_HOST:localhost}:${NAMING_SERVER_PORT:8761}/eureka/

server:
  port: ${PORT:8081}