server:
  port: ${PORT:8561}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://${NAMING_SERVER_HOST:localhost}:${PORT_NAMING_SERVER:8761}/eureka
